### PR TITLE
Handle pods with failed initcontainers or weird statuses

### PR DESCRIPTION
**Pull request by aermakov-zalando**
Handle initContainers as well to avoid issues with pods that don't have a started container.

### CODE REVIEW

**Comment by aermakov-zalando** [comment]
👍

**Comment by hjacobs** [comment]
@aermakov-zalando is this still needed when we have https://github.com/zalando-incubator/kubernetes-on-aws/pull/1668 ?

**Comment by aermakov-zalando** [comment]
We don't know yet if the TTL controller actually works. Plus it could be useful for other users?

**Comment by hjacobs** [comment]
@aermakov-zalando OK, is this PR code now the actually tested code (after the fix of the fix)? I'm referring to https://github.com/zalando-incubator/kubernetes-on-aws/pull/1674

**Comment by aermakov-zalando** [comment]
It ran on my machine. :) We'll roll out the fix to all clusters soon.

**Pull request merged**
